# Official Qt Multimedia packages supply FFmpeg DLLs without MSVC import
# libraries. Derive build-owned link metadata from those exact DLL exports.
function(ravo_windows_import_library runtime component output)
  if(NOT MSVC)
    message(FATAL_ERROR "Ravo Windows FFmpeg import generation requires MSVC")
  endif()
  find_program(_ravo_dumpbin NAMES dumpbin REQUIRED)
  if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(ARM64|arm64|aarch64)$")
    set(machine ARM64)
  elseif(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(machine X64)
  elseif(CMAKE_SIZEOF_VOID_P EQUAL 4)
    set(machine X86)
  else()
    message(FATAL_ERROR "Unsupported Windows FFmpeg target architecture")
  endif()
  set(directory "${CMAKE_BINARY_DIR}/_deps/ffmpeg-import")
  set(library "${directory}/${component}.lib")
  set(definition "${directory}/${component}.def")
  set(stamp "${directory}/${component}.sha256")
  file(SHA256 "${runtime}" identity)
  string(APPEND identity "|${machine}|${CMAKE_AR}")
  if(EXISTS "${library}" AND EXISTS "${stamp}")
    file(READ "${stamp}" previous)
    if(previous STREQUAL identity)
      set(${output} "${library}" PARENT_SCOPE)
      return()
    endif()
  endif()
  execute_process(COMMAND "${_ravo_dumpbin}" /nologo /exports "${runtime}"
    RESULT_VARIABLE result OUTPUT_VARIABLE exports ERROR_VARIABLE errors)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Cannot read FFmpeg DLL exports: ${exports}\n${errors}")
  endif()
  string(REPLACE "\r" "" exports "${exports}")
  string(REPLACE "\n" ";" rows "${exports}")
  set(symbols "")
  foreach(row IN LISTS rows)
    if(row MATCHES "^[ \t]+[0-9]+[ \t]+[0-9A-Fa-f]+[ \t]+[0-9A-Fa-f]+[ \t]+([A-Za-z_][A-Za-z0-9_]*)")
      list(APPEND symbols "${CMAKE_MATCH_1}")
    endif()
  endforeach()
  if(NOT symbols)
    message(FATAL_ERROR "FFmpeg DLL has no named C exports: ${runtime}")
  endif()
  list(REMOVE_DUPLICATES symbols)
  list(JOIN symbols "\n" symbol_lines)
  get_filename_component(dll_name "${runtime}" NAME)
  file(MAKE_DIRECTORY "${directory}")
  file(WRITE "${definition}" "LIBRARY ${dll_name}\nEXPORTS\n${symbol_lines}\n")
  execute_process(COMMAND "${CMAKE_AR}" /nologo "/def:${definition}"
    "/machine:${machine}" "/out:${library}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output_text ERROR_VARIABLE errors)
  if(NOT result EQUAL 0 OR NOT EXISTS "${library}")
    message(FATAL_ERROR "Cannot generate FFmpeg MSVC import library: ${output_text}\n${errors}")
  endif()
  file(WRITE "${stamp}" "${identity}")
  message(STATUS "Generated MSVC import library from ${runtime}")
  set(${output} "${library}" PARENT_SCOPE)
endfunction()
