#!/usr/bin/env python3
"""Generate the C runtime mode configuration from the active source-roots lock."""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
FREECM_ROOT = REPO_ROOT / "FreeCM"
if str(FREECM_ROOT) not in sys.path:
    sys.path.insert(0, str(FREECM_ROOT))

from configs.source_roots import dev_mode_from_lock_data  # noqa: E402
from freecm.jsonc import loads_jsonc  # noqa: E402


def checkout_persistence_id(repo_root: Path) -> str:
    """Return a stable, path-scoped identifier safe for a directory component."""
    real_path = str(repo_root.resolve())
    return hashlib.sha256(real_path.encode("utf-8")).hexdigest()[:12]


def load_lock_data(repo_root: Path, lock_file: Path | None = None) -> tuple[Path, dict[str, Any]]:
    if lock_file is None:
        active_path = repo_root / "source_roots.lock.jsonc"
        template_path = repo_root / "source_roots.lock.jsonc.in"
        lock_path = active_path if active_path.is_file() else template_path
    else:
        lock_path = lock_file

    if not lock_path.is_file():
        raise FileNotFoundError(f"Missing source-roots lock file: {lock_path}")
    data = loads_jsonc(lock_path.read_text(encoding="utf-8"), path_label=str(lock_path))
    if not isinstance(data, dict):
        raise ValueError(f"Invalid source-roots lock file (expected object): {lock_path}")
    return lock_path, data


def write_runtime_config(output: Path, *, dev_mode: bool, checkout_id: str) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        "\n".join(
            (
                "// Generated by configs/generate_build_runtime_config.py. Do not edit manually.",
                "#pragma once",
                "",
                f"#define DT_BUILD_DEVMODE {1 if dev_mode else 0}",
                f'#define DT_BUILD_CHECKOUT_ID "{checkout_id}"',
                "",
            )
        ),
        encoding="utf-8",
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate DarkTableNext runtime persistence configuration."
    )
    parser.add_argument("--repo-root", default=str(REPO_ROOT), help="Repository root path")
    parser.add_argument("--output", required=True, help="Generated C header path")
    parser.add_argument(
        "--lock-file",
        help="Optional source-roots lock file; defaults to the active lock then the template",
    )
    args = parser.parse_args(argv)

    repo_root = Path(args.repo_root)
    lock_file = Path(args.lock_file) if args.lock_file else None
    lock_path, lock_data = load_lock_data(repo_root, lock_file)
    dev_mode = dev_mode_from_lock_data(lock_data, path_label=lock_path)
    checkout_id = checkout_persistence_id(repo_root)
    write_runtime_config(Path(args.output), dev_mode=dev_mode, checkout_id=checkout_id)
    print(
        f"runtime mode: DevMode={'true' if dev_mode else 'false'} "
        f"checkoutPersistenceID={checkout_id} lock={lock_path}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
